name: eco_trade
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0" # Adicione esta linha!

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1 # Use a versão mais recente
  flutter_markdown: ^0.6.18

  dio: ^5.4.3+1
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  geocoding: ^4.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  google_maps_flutter: ^2.6.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Adicionado para incluir imagens no projeto
  assets:
    - assets/images/
